name: Build and push new dev tools image
on:
  push:
    branches:
      - "master"
    paths:
      - "infra/build/**"
      - ".github/workflows/build-push-cft-devtools.yml"
env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}

jobs:
  build-push-dev-tools:
    name: Build and push new CFT dev tools image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build
        run: |-
          gcloud auth configure-docker -q
          cd infra/build && make build-image-developer-tools

      - name: Push
        run: |-
          cd infra/build && make release-image-developer-tools
