name: TFLint blueprint ruleset

on:
  push:
    branches:
      - 'main'
    paths:
      - 'tflint-ruleset-blueprint/**'
      - '.github/workflows/go-tflint-plugin.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'tflint-ruleset-blueprint/**'
      - '.github/workflows/go-tflint-plugin.yml'

concurrency:
  group: '${{github.workflow}}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  unit:
    name: ${{ matrix.operating-system }} unit tests
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash
        working-directory: 'tflint-ruleset-blueprint'
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: tflint-ruleset-blueprint/go.mod
        cache-dependency-path: tflint-ruleset-blueprint/go.sum
    - run: |-
        make test
  releaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tflint-ruleset-blueprint'
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: 'tflint-ruleset-blueprint/go.mod'
    - run: echo "GORELEASER_CURRENT_TAG=v0.0.0" >> $GITHUB_ENV # sample tag for testing goreleaser
    - run: echo "${{env.GORELEASER_CURRENT_TAG}}"
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
      with:
        version: latest
        args: release --clean --skip=validate,publish
        workdir: tflint-ruleset-blueprint
