name: release-tflint

on:
  push:
    tags:
    - tflint-ruleset-blueprint/v*.*.*

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tflint-ruleset-blueprint'
    steps:
    - name: Checkout
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: 'tflint-ruleset-blueprint/go.mod'
    - run: echo "GORELEASER_CURRENT_TAG=${GITHUB_REF#refs/tags/tflint-ruleset-blueprint/}" >> $GITHUB_ENV
    - run: echo "${{env.GORELEASER_CURRENT_TAG}}"
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
      with:
        version: latest
        args: release --clean --skip=validate,publish
        workdir: tflint-ruleset-blueprint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: upload
      run: |
          gh release upload "tflint-ruleset-blueprint/${{env.GORELEASER_CURRENT_TAG}}" dist/tflint-ruleset-blueprint_*.zip dist/checksums.txt --repo ${{ github.repository }} --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
