name: Test devtools image build
on:
  pull_request:
    branches:
      - "master"
    paths:
      - "infra/build/**"
      - ".github/workflows/test-cft-devtools.yml"

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-dev-tools:
    name: Build CFT dev tools image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Build
        run: |-
          cd infra/build && make build-image-developer-tools
